### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by jcampbell05** [Bottr-js/Bottr#11]
We should move documentation out to Github Pages like Cocoapods (https://guides.cocoapods.org/) and document some of the API methods.

**Comment by vutran** [comment]
I like this idea. Docs should be a part of the repo so as API changes, we can update the docs/tests accordingly. Using the Wiki for API documentation can tend to cause some frustration of keeping them in sync.

**Comment by jcampbell05** [comment]
Moved into a Github Page
