### ISSUE TITLE
Update help text

### ISSUE THREAD

**Issue by gokaygurcan** [Bottr-js/Bottr#15]
Hello,

When you type `bottr-cli -h` you get this:

``` bash
  Usage: index [options] [command]


  Commands:

    init
    start
    build

  Options:

    -h, --help     output usage information
    -V, --version  output the version number
```

Usage section is not representing the actual usage. 

I know, it's not a big deal, but it'd be nice to have the correct info.

Thanks in advance.

**Comment by jcampbell05** [comment]
@gokaygurcan  Thanks for this. Do you have a link for where you saw this ?

**Comment by gokaygurcan** [comment]
Hello @jcampbell05,

I see it when I type `npm install -g bottr-cli && bottr-cli -h` into my terminal.

**Comment by jcampbell05** [comment]
@gokaygurcan Cool, so I will be pushing an update soon - `init` and `start` should still be valid.

**Comment by gokaygurcan** [comment]
Perfect! Thanks, and good luck!

**Comment by jcampbell05** [comment]
Should be fixed in latest version.
