### ISSUE TITLE
Examples out of date? 

### ISSUE THREAD

**Issue by sandeep** [Bottr-js/Bottr#18]
Following instructions here: 
https://github.com/Bottr-js/Bottr/wiki/Creating-a-new-project

Results in : 
```
$ bottr-cli test

  Usage: bottr-cli [options] [command]


  Commands:

    init  
    start 
    build 

  Options:

    -h, --help     output usage information
    -V, --version  output the version number
```

Additionally the code output by `bottr-cli init` is not the same as the example.

**Comment by jcampbell05** [comment]
@sandeep good catch, will update these now

**Comment by ummahusla** [comment]
I had this issue yesterday. We are going to update the docs very soon!

For now, please run `bottr-cli start` , it should fix this issue for now.

**Comment by jcampbell05** [comment]
I've just gone through the Wiki and updated the docs to correctly instruct you to run `bottr-cli start` and open `localhost:3000`.

Let me know if this works for you.

**Comment by ummahusla** [comment]
@jcampbell05 Will test it in the evening
