### ISSUE TITLE
Move clients into new folder

### ISSUE THREAD

**Issue by vutran** [Bottr-js/Bottr#25]
We should begin moving the different clients to a new folder `lib/clients` and also provide an interface to allow building clients easily which should also contribute towards the effort in #12

**Comment by jcampbell05** [comment]
@vutran Do you want to take the lead ? This may be a great way of introducing you to the project. 

Once we've done this then we can tackle #12 :)

**Comment by vutran** [comment]
Yeah, I'll take this.

**Comment by tjwudi** [comment]
We could probably pull clients out as plugins, and provide endpoint in main repository to add plugin. This allows us to extend to other medias like Slack, wechat and so on.

**Comment by jcampbell05** [comment]
Yeah that will make a lot of sense. I'll need something like that for when I add HTTP Events into the framework since I'll need a way of routing the event to the original client the user came from.

**Comment by jcampbell05** [comment]
@tjwudi would you like to join our slack btw?

**Comment by tjwudi** [comment]
@jcampbell05 of course. I am also now investigating building a bot app :)

**Comment by jcampbell05** [comment]
@tjwudi let me know your email so I can invite you

**Comment by tjwudi** [comment]
@jcampbell05 https://privnote.com/QJN295bm#gRiUohBbU

**Comment by jcampbell05** [comment]
@tjwudi  let me know if you got the invite.

**Comment by vutran** [comment]
PR #31 is ready for review. I'll be submitting a new PR for the interface with the current implementation.

**Comment by jcampbell05** [comment]
Merged #31 which does exactly this
