### ISSUE TITLE
Failed to get the app working in the tutorial

### ISSUE THREAD

**Issue by sbose78** [Bottr-js/Bottr#39]
Hi,

I found this project very interesting and was looking to contribute as well. Prior to that, wanted to build something for myself but ...

Tutorial in the wiki doesn't seem to be working - 
https://gist.github.com/sbose78/bb5da79ea6332b539c3d9c88c6a1e3ff

Reached till the testing of the deployed app.
https://github.com/Bottr-js/Bottr/wiki/Deploying-Your-Bot#testing-it-out

I send a message from Facebook messenger which doesn't trigger anything on https://dry-badlands-98286.herokuapp.com/   and also https://dry-badlands-98286.herokuapp.com/webhook doesn't return a decent response :) 

Could you help me debug?

--
Shoubhik

**Comment by sbose78** [comment]
OK, the messages arrived. with a lot of delay though - no worries.

**Comment by jcampbell05** [comment]
@sbose78 great to hear that it arrived. Would love to know if you can find out why they took so long. Perhaps heroku was spinning up it's servers ?

Anysways let me know how you get on and I would love for you to contribute :)
