### ISSUE TITLE
Make Our Site Look Awesome

### ISSUE THREAD

**Issue by jcampbell05** [Bottr-js/Bottr#43]
We have a new site but it still needs a lot of work.

https://bottr.co/

1. Tidy up vertical rhythmn spacing.
2. Fix it on mobile devices
3. Make sure it is obvious to the reader what it is, maybe add more examples of the platforms and services we support.

**Comment by aaronraff** [comment]
I would like to help out with this. Would it be acceptable to choose one step and submit a pull request for just that step or are you looking for one request that fulfills all of these requirements?

**Comment by jcampbell05** [comment]
@aaronraff  It would be acceptable to do one step :)

**Comment by geoffdavis92** [comment]
@aaronraff Do you want any help, or do are you good?

**Comment by aaronraff** [comment]
@geoffdavis92 If you would like to contribute, I'm sure we could split up the work!

**Comment by aaronraff** [comment]
@jcampbell05 Maybe I am missing something but I do not believe that the repository contains your front-end files for the Bottr website. Please let me know how I can obtain these files so that I can contribute to this project.

**Comment by jcampbell05** [comment]
@aaronraff they should be in the gh-pages repository. We use middleman to generate it right now.

**Comment by aaronraff** [comment]
@jcampbell05 I found them, thank you.

**Comment by geoffdavis92** [comment]
#52  

Cleaned up the Sass and HTML some, made a few minor design changes.

**Comment by geoffdavis92** [comment]
PR #53 

Added more responsive styling; looks great on the Chrome DevTools emulators. Again, you can preview this [here](https://geoffdavis.info/Bottr/).

**Comment by jcampbell05** [comment]
@geoffdavis92  Looking amazing now! Will close this.
