### ISSUE TITLE
Grammar change on website

### ISSUE THREAD

**Issue by PXgamer** [Bottr-js/Bottr#45]
This obviously isn't that important, just something I noticed.

On the homepage of the [site](https://bottr.co/) in the box saying `The World's Simpilest Bot Framework` it uses `Simpilest` instead of `Simplest`.

It also says this in the homepage example code.

I'm guessing it should be `The world's simplest bot framework` as per the [`package.json`](https://github.com/Bottr-js/Bottr/blob/master/package.json) file.

**Comment by jcampbell05** [comment]
@PXgamer Good catch! I'll try to get that fixed up.

**Comment by PXgamer** [comment]
NP. I also was gunna do a pull request to change the README.md logo to the following.
![Logo](https://bottr.co/images/logo-d65664e2.png)
Would that be alright?

**Comment by geoffdavis92** [comment]
Can this be closed?

**Comment by vutran** [comment]
Thanks!
