### ISSUE TITLE
replace mentions of "pozi" with "bottr"

### ISSUE THREAD

**Issue by vutran** [Bottr-js/Bottr#56]
[Bottr-App](https://github.com/Bottr-js/Bottr-App) still has references to the old name "pozi". This should be renamed to "bottr".

**Comment by arpit1997** [comment]
Can you tell where it is mentioned that "Bottr-App" as "pozi". The above link points to a different repository so if it is an issue of [that](https://github.com/Bottr-js/Bottr-App) then you can move this issue in that repository. 
Thank you. :smile:

**Comment by vutran** [comment]
@arpit1997 The issues are currently consolidated to single repo as to provide a single place for management of opened issues.

[Here](https://github.com/Bottr-js/Bottr-App/search?utf8=%E2%9C%93&q=pozi) is a quick link for the mentions of "pozi".

Hope that helps.

**Comment by arpit1997** [comment]
Thank you very much for your response. I thought that it might be a mistake of opening this issue here but i got your point. I would like to give it a try. I suppose it is not much work to do. :smile: :+1:
