### ISSUE TITLE
Get Started button broken

### ISSUE THREAD

**Issue by ummahusla** [Bottr-js/Bottr#61]
On the [**bottr.co**](http://bottr.co) homapge - [**Get Started**](https://bottr.co/docs/install) button is broken and lead to 404 page.

**Comment by jcampbell05** [comment]
Cool just needs updating to point to https://github.com/Bottr-js/Bottr/wiki/Creating-a-new-project

**Comment by ummahusla** [comment]
@jcampbell05 Where bottr.co website is currently hosted? I though it's GitHub pages.

**Comment by jcampbell05** [comment]
@ummahusla It is hosted on Github Pages yes :)

**Comment by ummahusla** [comment]
@jcampbell05 Yeah as I though but I can't find the repo for it. Can you send me the link please.

**Comment by jcampbell05** [comment]
@ummahusla  its this repo but on the `gh-pages` branch

**Comment by ummahusla** [comment]
@jcampbell05 Nice one, #62 👍
