### ISSUE TITLE
bottr: command not found

### ISSUE THREAD

**Issue by ayushj31** [Bottr-js/Bottr#63]
I tried creating a new project. Following are steps:
1. brew install node
2. sudo npm install -g bottr-cli
3. mkdir ecobot && cd ecobot && bottr init

It creates and redirect to directory "ecobot" but unable to find bottr.
says: **bottr: command not found**

**Comment by jcampbell05** [comment]
@ayushj31 Could you try `bottr-cli init` its possible the latest version of the tool hasn't been released. I'll try and upload a new version today.

**Comment by klugjo** [comment]
Same issue here

```
bottr-cli init
```

worked

**Comment by jcampbell05** [comment]
@klugjo  Thanks for confirming, I'll make sure to get a new version up today which fixes this :)

**Comment by jcampbell05** [comment]
Should be fixed, if you upgrade to `bottr-cli@0.1.3`
