### ISSUE TITLE
Fix a broken link on 'Installation' page of docs to: Creating your fisrt bot

### ISSUE THREAD

**Issue by ivarsmas** [Bottr-js/Bottr#64]
In the documentation in the first page: [Installation](https://bottr.co/docs.html) at the end of the page there are a broken link, left /docs on href, it need change: 

https://bottr.co/creating-your-first-bot.html by: 

https://bottr.co/docs/creating-your-first-bot.html

**Comment by jcampbell05** [comment]
@ivarsmas Hey are you able to submit a PR for this ?

**Comment by jcampbell05** [comment]
Should be fixed now
