### ISSUE TITLE
Bottr featured on Javascript Daily's twitter

### ISSUE THREAD

**Issue by geoffdavis92** [Bottr-js/Bottr#68]
@jcampbell05

[Link to tweet here](https://twitter.com/JavaScriptDaily/status/792067423314776064)

**Comment by jcampbell05** [comment]
@geoffdavis92 Amazing! Thanks for spotting this :) Was wondering why we had another epxlosion of activity.

Btw are you on our slack ?

**Comment by geoffdavis92** [comment]
@jcampbell05 I am not; I actually posted in one of my PRs this morning about that 😄 . You can email me an invite at gdavis@archermalmo.com

**Comment by jcampbell05** [comment]
@geoffdavis92 Sent :) sorry about that.
