### ISSUE TITLE
https://bottr.co/examples page is broken.

### ISSUE THREAD

**Issue by stuartcw** [Bottr-js/Bottr#75]
Hi,

I reached [https://bottr.co/examples](https://bottr.co/examples) while checking the documentation on [https://bottr.co](https://bottr.co) but that link seems to be broken.

Regards

**Comment by jcampbell05** [comment]
Cheers for this, seems to be something weird with the server we are using - will have this fixed this week.

**Comment by jcampbell05** [comment]
Duplicate of #70
