### ISSUE TITLE
Website displays Apace default page

### ISSUE THREAD

**Issue by geoffdavis92** [Bottr-js/Bottr#80]
Seems like there's an error with the server setup for the website; http://bottr.co shows this page instead:

![bottr.co on 15-2-2017](http://image.prntscr.com/image/0ca2ca209beb4e6f8b677e5f6498f75c.png)

@jcampbell05

**Comment by jcampbell05** [comment]
Interesting I'll take a look

**Comment by mrredbit** [comment]
Since the site is down, the document cannot be view. 
Anywhere else I can see the document / guide? Really wanna try it out.

**Comment by jcampbell05** [comment]
@mrredbit I have it back up but it seems github doesn't serve HTTPS to custom domains I'm currently setting up a cloudflare which will resolve this :)

**Comment by jcampbell05** [comment]
This should be resolved now, let me know.

Check it here.
https://bottr.co/

**Comment by mrredbit** [comment]
@jcampbell05 Not sure if this is the correct place to report, just to let you know https://bottr.co/examples still returning 404 at the moment.

**Comment by jcampbell05** [comment]
@mrredbit good catch :) I'll try to get a better examples page up :)

**Comment by geoffdavis92** [comment]
@jcampbell05 I will take a look at that as well. That's partly how/why I found the Apache error :P

**Comment by jcampbell05** [comment]
@geoffdavis92 awesome :) would love to see what you come up with :)
