### ISSUE TITLE
Examples link routes to dead link

### ISSUE THREAD

**Issue by garrettmac** [Bottr-js/Bottr#83]
I'd take a look at the examples hyperlink. It's a dead link.

**Comment by jcampbell05** [comment]
@garrettmac  seems the server has gone down I'll have a look :)

**Comment by ummahusla** [comment]
Closing this, because it's a duplicate of #44.

Currently, all the examples are located in [**Bottr-Examples**](https://github.com/Bottr-js/Bottr-Examples) repository. At some point, we need to migrate it into this repository to `gh-pages` branch.
